project:
  type: website

website:
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introducci√≥n"
        href: index.qmd
      - section: "Basics"
        href: about.qmd
        contents:
          - index.qmd

format:
  html:
    theme: cosmo

